version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: social_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: social_redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: social_api
  #   depends_on:
  #     - postgres
  #     - redis
  #   env_file:
  #     - .env
  #   ports:
  #     - '3000:3000'
  #   command: ['npm', 'run', 'start:dev']

volumes:
  postgres_data:
